Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [29]:
import numpy as np
a = int(input ('Введите число элементов массива numpy array:'))
np.arange(a-1,-1,-1)

Введите число элементов массива numpy array:10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [34]:
a = int(input ('Введите число элементов массива numpy array:'))
np.diag(np.arange(a-1,-1,-1))

Введите число элементов массива numpy array:10


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.sum(np.arange(a-1,-1,-1))

45

Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [37]:
a= np.array(
    [
        [4,2,1],
        [1,3,0],
        [0,5,4]
    ]
)
b= np.array([4,12,-3])
from numpy import linalg
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [39]:
# проверяем верность
np.allclose(np.dot(a,linalg.solve(a,b)),b)

True

Задание 4
Матрица в виде numpy array users_stats.

На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [61]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

similar_user_cos =0

for row in users_stats:            # делаем перебор всех строк матрицы 
    current_user_cos = cosine(next_user_stats,row)
    print(row, current_user_cos)
    if similar_user_cos < current_user_cos:
        similar_user_cos = current_user_cos
        similar_user = row

print("Самый похожий пользователь: ",similar_user) 

[2 1 0 0 0 0] 0.19999999999999996
[1 1 2 1 0 0] 0.8451542547285165
[2 0 1 0 0 0] 0.3999999999999999
[1 1 2 1 0 1] 0.7905694150420948
[0 0 1 2 0 0] 0.3999999999999999
[0 0 0 0 0 5] 0.0
[1 0 0 0 0 0] 0.0
[0 1 1 0 0 0] 0.9486832980505138
[0 0 0 1 1 3] 0.0
[1 0 0 2 1 4] 0.0
Самый похожий пользователь:  [0 1 1 0 0 0]
